spring.application.name=table21
spring.datasource.url=jdbc:mariadb://localhost:3306/pos
spring.datasource.username=root
spring.datasource.password=Qwerty@123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=MariaDB-Hikari-Pool
spring.main.banner-mode=off